#!/usr/bin/env expect -f

set script_dir [file dirname [file normalize [info script]]]
set phxargs_bin "$script_dir/../build/phxargs"

spawn $phxargs_bin -o "$script_dir/open-tty-script.sh"

send "arg1 arg2\r"
send \x04

set timeout 60
expect {
  "From stdin: arg1 arg2" {
    expect "Enter input:"
    send "abc\r"
    expect "Received: abc"
    expect eof
  }
  timeout {
    puts "Timeout occurred"
    exit 1
  }
  eof {
    puts "EOF occurred unexpectedly"
    exit 1
  }
}

catch wait result
set exit_status [lindex $result 3]
exit $exit_status   
